"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { GraduationCap, Newspaper, PenTool, Building2, ArrowRight } from "lucide-react";
import { TiltCard } from "./TiltCard";

const useCases = [
  {
    icon: GraduationCap,
    audience: "Educators",
    headline: "Protect Academic Integrity",
    description:
      "Quickly verify whether student submissions were written by hand or generated by AI. Sentence-level scoring shows exactly which parts are suspicious — not just a vague percentage.",
    gradient: "135deg, #2563EB, #3B82F6",
    glow:     "rgba(59,130,246,0.5)",
    border:   "rgba(59,130,246,0.25)",
    tag:      "For Schools & Universities",
  },
  {
    icon: Newspaper,
    audience: "Publishers & Editors",
    headline: "Keep Your Content Human",
    description:
      "Before an article goes live, run it through TruthLens. Catch AI-drafted copy that slipped through your workflow and maintain the editorial standards your readers trust.",
    gradient: "135deg, #7C3AED, #8B5CF6",
    glow:     "rgba(139,92,246,0.5)",
    border:   "rgba(139,92,246,0.25)",
    tag:      "For Media & Content Teams",
  },
  {
    icon: PenTool,
    audience: "Freelancers & Agencies",
    headline: "Prove Your Work is Original",
    description:
      "Show clients that the copy you delivered was genuinely crafted. Export a full report and attach it as proof — a simple way to differentiate yourself in an AI-flooded market.",
    gradient: "135deg, #059669, #10B981",
    glow:     "rgba(16,185,129,0.5)",
    border:   "rgba(16,185,129,0.25)",
    tag:      "For Creators & Agencies",
  },
  {
    icon: Building2,
    audience: "HR & Hiring Teams",
    headline: "Evaluate Authentic Candidates",
    description:
      "Cover letters and written assessments reveal a lot — but only if they're real. Instantly flag AI-generated applications so you can focus on the humans behind them.",
    gradient: "135deg, #D97706, #F59E0B",
    glow:     "rgba(245,158,11,0.5)",
    border:   "rgba(245,158,11,0.25)",
    tag:      "For Recruitment",
  },
];

const container = {
  hidden:  { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.12 } },
};

const item = {
  hidden:  { opacity: 0, y: 40 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: "easeOut" as const } },
};

export function Testimonials() {
  return (
    <section
      className="relative py-24 lg:py-36 overflow-hidden"
      style={{ background: "#050A14" }}
    >
      {/* bg glow */}
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          background:
            "radial-gradient(ellipse 80% 50% at 50% 100%, rgba(37,99,235,0.07) 0%, transparent 70%)",
        }}
      />

      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-80px" }}
          transition={{ duration: 0.6 }}
          className="text-center max-w-3xl mx-auto mb-20"
        >
          <span className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-blue-500/30 bg-blue-500/10 text-sm font-medium text-blue-300 mb-5">
            Who It&apos;s For
          </span>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black text-white mb-5">
            Built for Everyone Who{" "}
            <span className="shimmer-text">Values Truth</span>
          </h2>
          <p className="text-lg text-slate-400">
            Whether you&apos;re a teacher, editor, writer, or recruiter — TruthLens gives you the confidence to trust the text you read.
          </p>
        </motion.div>

        {/* Cards */}
        <motion.div
          variants={container}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-80px" }}
          className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-16"
        >
          {useCases.map((uc) => (
            <motion.div key={uc.audience} variants={item}>
              <TiltCard tiltMaxAngle={6} glareEnable className="h-full">
                <div
                  className="neon-card relative h-full rounded-2xl p-8 border"
                  style={{
                    background:     "rgba(15,23,42,0.85)",
                    borderColor:    uc.border,
                    backdropFilter: "blur(12px)",
                  }}
                  onMouseEnter={(e) => {
                    (e.currentTarget as HTMLElement).style.boxShadow = `0 0 50px ${uc.glow.replace("0.5", "0.2")}`;
                  }}
                  onMouseLeave={(e) => {
                    (e.currentTarget as HTMLElement).style.boxShadow = "none";
                  }}
                >
                  {/* Tag */}
                  <span
                    className="inline-block px-3 py-1 rounded-full text-xs font-semibold mb-5"
                    style={{
                      background: `linear-gradient(${uc.gradient})`,
                      opacity: 0.85,
                      color: "white",
                    }}
                  >
                    {uc.tag}
                  </span>

                  <div className="flex items-start gap-5">
                    {/* Icon */}
                    <div
                      className="w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0 mt-1"
                      style={{
                        background: `linear-gradient(${uc.gradient})`,
                        boxShadow:  `0 0 18px ${uc.glow}`,
                      }}
                    >
                      <uc.icon className="w-6 h-6 text-white" />
                    </div>

                    <div>
                      <h3 className="text-xl font-bold text-white mb-2">{uc.headline}</h3>
                      <p className="text-slate-400 leading-relaxed">{uc.description}</p>
                    </div>
                  </div>
                </div>
              </TiltCard>
            </motion.div>
          ))}
        </motion.div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center"
        >
          <Link
            href="/scan"
            className="inline-flex items-center gap-2 px-8 py-4 rounded-full font-semibold text-white transition-all duration-300 hover:scale-105"
            style={{
              background: "linear-gradient(135deg,#2563EB 0%,#06B6D4 100%)",
              boxShadow:  "0 0 30px rgba(37,99,235,0.4)",
            }}
          >
            Try It Free — No Sign-up
            <ArrowRight className="w-5 h-5" />
          </Link>
        </motion.div>
      </div>
    </section>
  );
}
