import { NextRequest, NextResponse } from "next/server";

const MAX_TEXT_LENGTH = 200000;

export async function POST(request: NextRequest) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      { error: "API key not configured", code: "NO_API_KEY" },
      { status: 503 }
    );
  }

  let body: { text?: string };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  const { text } = body;
  if (!text || typeof text !== "string" || text.trim().length === 0) {
    return NextResponse.json({ error: "Text is required" }, { status: 400 });
  }

  if (text.length > MAX_TEXT_LENGTH) {
    return NextResponse.json(
      { error: `Text exceeds maximum length of ${MAX_TEXT_LENGTH.toLocaleString()} characters` },
      { status: 400 }
    );
  }

  const prompt = `Analyze the following text and determine the probability that it was generated by AI versus written by a human.

Return ONLY a valid JSON object with this exact structure, no markdown, no explanation:
{
  "score": <overall_ai_probability_0_to_1>,
  "sentence_scores": [
    {"sentence": "<exact_sentence_text>", "score": <ai_probability_0_to_1>},
    ...
  ]
}

Rules:
- All score values must be between 0.0 and 1.0
- 0.0 = definitely human written, 1.0 = definitely AI generated
- Split the text into individual sentences and score each one
- The overall score should reflect the weighted average across all sentences
- Return every sentence from the original text

Text to analyze:
"""
${text}
"""`;

  try {
    const res = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: { temperature: 0.1 },
        }),
      }
    );

    if (!res.ok) {
      const errBody = await res.json().catch(() => null);
      console.error("Gemini REST error:", res.status, errBody);
      return NextResponse.json(
        { error: errBody?.error?.message || `Gemini API error (${res.status})` },
        { status: 502 }
      );
    }

    const geminiData = await res.json();
    const raw = geminiData.candidates?.[0]?.content?.parts?.[0]?.text?.trim() ?? "";
    const jsonString = raw.replace(/^```(?:json)?\n?/, "").replace(/\n?```$/, "");
    const data = JSON.parse(jsonString);

    return NextResponse.json(data);
  } catch (error) {
    console.error("Gemini request failed:", error);
    return NextResponse.json(
      { error: "Unable to reach AI detection service. Please try again." },
      { status: 502 }
    );
  }
}
