import { AnalysisResult } from "./analyzer";

const STORAGE_KEY = "truthlens_scan_history";
const MAX_HISTORY_ITEMS = 50;

export interface HistoryItem extends AnalysisResult {
  savedAt: string;
}

export function saveToHistory(result: AnalysisResult): void {
  if (typeof window === "undefined") return;

  try {
    const existing = getHistory();
    const newItem: HistoryItem = {
      ...result,
      savedAt: new Date().toISOString(),
    };

    // Check for duplicate (same text)
    const filtered = existing.filter((item) => item.text !== result.text);
    
    // Add new item at the beginning
    const updated = [newItem, ...filtered].slice(0, MAX_HISTORY_ITEMS);
    
    localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
  } catch (error) {
    console.error("Failed to save to history:", error);
  }
}

export function getHistory(): HistoryItem[] {
  if (typeof window === "undefined") return [];

  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (!stored) return [];
    
    const parsed = JSON.parse(stored) as HistoryItem[];
    return parsed;
  } catch (error) {
    console.error("Failed to get history:", error);
    return [];
  }
}

export function getHistoryItemById(id: string): HistoryItem | undefined {
  const history = getHistory();
  return history.find((item) => item.id === id);
}

export function deleteFromHistory(id: string): void {
  if (typeof window === "undefined") return;

  try {
    const existing = getHistory();
    const filtered = existing.filter((item) => item.id !== id);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(filtered));
  } catch (error) {
    console.error("Failed to delete from history:", error);
  }
}

export function clearHistory(): void {
  if (typeof window === "undefined") return;

  try {
    localStorage.removeItem(STORAGE_KEY);
  } catch (error) {
    console.error("Failed to clear history:", error);
  }
}

export function searchHistory(query: string): HistoryItem[] {
  const history = getHistory();
  if (!query.trim()) return history;

  const lowerQuery = query.toLowerCase();
  return history.filter(
    (item) =>
      item.text.toLowerCase().includes(lowerQuery) ||
      item.verdict.toLowerCase().includes(lowerQuery) ||
      new Date(item.scanDate).toLocaleDateString().toLowerCase().includes(lowerQuery)
  );
}

export function exportHistoryAsJSON(): string {
  const history = getHistory();
  return JSON.stringify(history, null, 2);
}

export function generateReport(result: AnalysisResult): string {
  const date = new Date(result.scanDate).toLocaleString();
  
  return `TRUTHLENS ANALYSIS REPORT
Generated: ${date}

=== OVERALL ASSESSMENT ===
Verdict: ${result.verdict.toUpperCase()}
AI Probability: ${result.overallScore}%
Plagiarism Score: ${result.plagiarismScore}%

=== TEXT STATISTICS ===
Word Count: ${result.wordCount}
Character Count: ${result.characterCount}
Reading Time: ${result.readingTime}
Sentences Analyzed: ${result.sentences.length}

=== SENTENCE BREAKDOWN ===
${result.sentences
  .map(
    (s, i) =>
      `[${i + 1}] AI Probability: ${Math.round(s.aiProbability * 100)}%\n${s.text}\n`
  )
  .join("\n")}

=== ANALYZED TEXT ===
${result.text}

---
Report generated by TruthLens - Preserve What's Human
`;
}
